<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <RootNamespace>Raptor21.OpenApi.Generics.Sample</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Raptor21.OpenApi.Generics.AspNetCore\Raptor21.OpenApi.Generics.AspNetCore.csproj" />
    </ItemGroup>

</Project>
